import os
from ui.theme import C

# ─── Folder paths (relative to the project root) ──────────────────────────────
HERE    = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPTS = os.path.join(HERE, "scripts")
SAMPLES = os.path.join(HERE, "samples")

# ─── Group Definitions ────────────────────────────────────────────────────────
GROUPS = [
    {
        "title":       "PDF Downloads",
        "description": "Download PDFs from Excel URL lists — with or without renaming.",
        "icon":        "📥",
        "accent":      C["cyan"],
        "tag":         "PDF · Excel",
        "count":       "2 tools",
        "tools": [
            {
                "title":       "PDF Download & Rename",
                "description": "Download PDFs from an Excel list of URLs and rename each file using a custom ID column.",
                "icon":        "⚡",
                "accent":      C["green"],
                "tag":         "PDF · Excel",
                "script":      os.path.join(SCRIPTS, "pdf_downloader_rename.py"),
                "sample":      os.path.join(SAMPLES, "sample_pdf_download_rename.xlsx"),
                "docs": {
                    "what": "Downloads PDF files from a list of URLs stored in an Excel file, then renames each downloaded file using a unique ID from another column in the same sheet.",
                    "when": "Use this when you have an Excel sheet with a column of PDF URLs and a column of IDs/names, and you want each PDF saved with its matching ID as the filename.",
                    "steps": [
                        ("Open the tool", "Click 'Launch →' on the PDF Download & Rename card."),
                        ("Select your Excel file", "Click 'Browse' and choose the .xlsx or .xls file that contains your URL list."),
                        ("Enter the URL column name", "Type the exact column header that contains the PDF URLs (e.g. 'URL' or 'Link'). It is case-sensitive."),
                        ("Enter the ID column name", "Type the exact column header whose values will be used as filenames (e.g. 'ID' or 'File Name'). Each PDF will be saved as <ID>.pdf."),
                        ("Enter the sheet name (optional)", "If your data is not on the first sheet, type the exact sheet name. Leave blank to use the first sheet."),
                        ("Click 'Start Download'", "The tool will begin downloading. A progress bar shows how many files are done. The log area shows each file's status in real time."),
                        ("Find your files", "When complete, a folder will open automatically. Files are saved to: Desktop → OUTPUT → PDF_Downloads_Renamed → <timestamp folder>."),
                    ],
                    "tips": [
                        "Make sure column names match exactly — including spaces and capitalisation.",
                        "If a URL is invalid or the PDF cannot be reached, that row is skipped and logged as an error.",
                        "Each run creates a new timestamped folder, so old downloads are never overwritten.",
                        "You can close the tool after downloading — files stay in the OUTPUT folder.",
                    ],
                    "output": "Desktop\\OUTPUT\\PDF_Downloads_Renamed\\YYYY-MM-DD_HH-MM-SS\\",
                },
            },
            {
                "title":       "PDF Downloader",
                "description": "Download PDFs from an Excel URL list. Keeps original filenames — no renaming.",
                "icon":        "📄",
                "accent":      C["cyan"],
                "tag":         "PDF",
                "script":      os.path.join(SCRIPTS, "pdf_downloader_only.py"),
                "sample":      os.path.join(SAMPLES, "sample_pdf_download_only.xlsx"),
                "docs": {
                    "what": "Downloads PDF files from a list of URLs stored in an Excel file. Each file is saved using the filename from the URL itself — no renaming is applied.",
                    "when": "Use this when you just need to bulk-download PDFs and the original filename from the URL is fine to keep.",
                    "steps": [
                        ("Open the tool", "Click 'Launch →' on the PDF Downloader card."),
                        ("Select your Excel file", "Click 'Browse' and choose the .xlsx or .xls file that contains your URL list."),
                        ("Enter the URL column name", "Type the exact column header that contains the PDF URLs (e.g. 'URL' or 'Download Link'). It is case-sensitive."),
                        ("Enter the sheet name (optional)", "If your data is not on the first sheet, type the exact sheet name. Leave blank to use the first sheet."),
                        ("Click 'Start Download'", "The tool downloads each PDF. Progress and status are shown in real time in the log area below."),
                        ("Find your files", "When complete, the output folder opens automatically. Files are saved to: Desktop → OUTPUT → PDF_Downloads_Only → <timestamp folder>."),
                    ],
                    "tips": [
                        "If two URLs have the same filename, the second will overwrite the first — rename them after if needed.",
                        "URLs must point directly to a .pdf file for best results.",
                        "Rows with blank or invalid URLs are skipped and noted in the log.",
                        "Each run creates a fresh timestamped folder, so previous runs are always preserved.",
                    ],
                    "output": "Desktop\\OUTPUT\\PDF_Downloads_Only\\YYYY-MM-DD_HH-MM-SS\\",
                },
            },
        ],
    },
    {
        "title":       "Printing",
        "description": "Send PDFs and documents to your default printer with batch, duplex, and order controls.",
        "icon":        "🖨️",
        "accent":      C["green"],
        "tag":         "Print · PDF",
        "count":       "3 tools",
        "tools": [
            {
                "title":       "SR No Stamp & Print",
                "description": "Stamp serial numbers onto PDFs from an Excel list, then print them in order via the default printer.",
                "icon":        "🔢",
                "accent":      C["green"],
                "tag":         "Print · PDF",
                "script":      os.path.join(SCRIPTS, "srno_stamp_print.py"),
                "sample":      os.path.join(SAMPLES, "sample_srno_stamp.xlsx"),
                "docs": {
                    "what": "A two-phase pipeline tool. Phase 1 reads an Excel file, matches filenames to PDFs in a folder, and stamps each PDF's serial number on the first page. Phase 2 sends the stamped PDFs to the default Windows printer in numbered order, in configurable batches.",
                    "when": "Use this when you have a batch of PDFs that need a unique serial number stamped before printing — for example dispatch documents, certificates, or application forms.",
                    "steps": [
                        ("Set default printer", "Before opening the tool, go to Windows Settings → Bluetooth & devices → Printers and set your printer as the default."),
                        ("Select your Excel file", "The Excel must have a column with the PDF filename (or part of it) and a column with the serial number to stamp."),
                        ("Enter column names", "Type the exact column headers for the filename column and the SR No column."),
                        ("Select PDF source folder", "Pick the folder containing the original PDF files."),
                        ("Adjust stamp settings", "Set font size, left margin, and top margin for the stamped number position."),
                        ("Configure print settings", "Set batch size, delays, and duplex options."),
                        ("Click Stamp & Print", "Phase 1 stamps all PDFs into the output folder. Phase 2 prints them in order. Use Pause/Resume anytime."),
                        ("Find your files", "Stamped PDFs and a job log are saved to Desktop → OUTPUT → SrNo_Stamp_Print → <timestamp>."),
                    ],
                    "tips": [
                        "The filename column should contain a value that appears in the PDF filename — it does not need to be an exact match.",
                        "Missing PDFs are logged to missing.csv in the output folder and skipped.",
                        "Auto-detect duplex edge detects portrait/landscape per file automatically.",
                        "Use Pause to stop between batches and check print quality before resuming.",
                    ],
                    "output": "Desktop\\OUTPUT\\SrNo_Stamp_Print\\YYYY-MM-DD_HH-MM-SS\\",
                },
            },
            {
                "title":       "Excel Order Print",
                "description": "Print PDFs in the exact row order defined by an Excel list, with retry logic and missing file warnings.",
                "icon":        "📋",
                "accent":      C["purple"],
                "tag":         "Print · PDF",
                "script":      os.path.join(SCRIPTS, "excel_print.py"),
                "sample":      os.path.join(SAMPLES, "sample_excel_print.xlsx"),
                "docs": {
                    "what": "Reads an Excel file, matches each row to a PDF by filename, and prints them in the exact order the rows appear in the sheet. If any PDFs are missing, it warns you and lets you choose to continue or abort. Failed prints are retried up to 3 times.",
                    "when": "Use this when the print order matters and is defined in an Excel file — for example printing application forms in a specific sequence for filing or distribution.",
                    "steps": [
                        ("Set default printer", "Go to Windows Settings → Printers and set your target printer as the default."),
                        ("Select Excel file", "Pick the .xlsx file. The tool reads its columns and shows them as radio buttons."),
                        ("Select filename column", "Choose the column that contains the PDF filenames or identifiers."),
                        ("Select PDF folder", "Pick the folder containing the PDF files."),
                        ("Configure print settings", "Set batch size, delays, and duplex options."),
                        ("Click Print in Excel Order", "The tool matches each row to a PDF and prints in sequence. If missing PDFs are found, a warning dialog lets you continue or abort."),
                    ],
                    "tips": [
                        "Matching is partial — a row value of 'ABC123' will match a file named 'prospect_ABC123_form.pdf'.",
                        "Each failed print is retried 3 times automatically before being marked as failed.",
                        "A job.log file is saved to the output folder with a full timestamp record of every print.",
                        "Use Pause/Resume to stop mid-job without losing your place.",
                    ],
                    "output": "Desktop\\OUTPUT\\Excel_Print\\YYYY-MM-DD_HH-MM-SS\\",
                },
            },
            {
                "title":       "Quick Print",
                "description": "Add any files or folders and send them all to the default printer. Order doesn't matter.",
                "icon":        "⚡",
                "accent":      C["cyan"],
                "tag":         "Print",
                "script":      os.path.join(SCRIPTS, "quick_print.py"),
                "sample":      None,
                "docs": {
                    "what": "A simple bulk print tool. Add any mix of files or folders, configure batch and delay settings, and send everything to the default printer. No Excel file needed — just add and print.",
                    "when": "Use this when you have a pile of documents to print and the order doesn't matter. Supports PDFs and any file type Windows can print.",
                    "steps": [
                        ("Set default printer", "Go to Windows Settings → Printers and set your target printer as the default."),
                        ("Add files or folders", "Click 'Add Files' to pick individual files, or 'Add Folders' to include everything inside a folder (including subfolders). You can mix both."),
                        ("Configure print settings", "Set batch size, delay between prints, delay between batches, and duplex options."),
                        ("Click Print All", "All files are sent to the default printer in batches. Progress, stats, and per-file status update in real time."),
                        ("Use Pause/Resume", "Click Pause at any time to hold the queue. Click Resume to continue from where it stopped."),
                    ],
                    "tips": [
                        "Files are printed using Windows ShellExecute — any file type that has a default print handler will work.",
                        "Duplex settings only apply to PDF files. Other file types use their own default print settings.",
                        "A job.log is saved to Desktop → OUTPUT → Quick_Print → <timestamp> with a full record of the job.",
                        "Use a small delay (2-3 sec) for local printers and a larger one (5-10 sec) for network printers.",
                    ],
                    "output": "Desktop\\OUTPUT\\Quick_Print\\YYYY-MM-DD_HH-MM-SS\\",
                },
            },
        ],
    },
]

# ─── Individual Service Definitions ───────────────────────────────────────────
SERVICES = [
    {
        "title":       "PDF Watermark",
        "sample":      os.path.join(SAMPLES, "sample_pdf_watermark.pdf"),
        "description": "Add a diagonal watermark (text) to one or multiple PDF files in one go.",
        "icon":        "🔏",
        "accent":      C["purple"],
        "tag":         "PDF",
        "script":      os.path.join(SCRIPTS, "pdf_watermark.py"),
        "docs": {
            "what": "Adds a customisable diagonal watermark text (e.g. CONFIDENTIAL, MSME, DRAFT) to every page of one or more PDF files. You can control the text, font size, rotation angle, opacity, and colour.",
            "when": "Use this when you need to stamp PDFs before sharing them — for example marking documents as confidential, draft, or with a company/brand name.",
            "steps": [
                ("Open the tool", "Click 'Launch →' on the PDF Watermark card from the Home screen."),
                ("Select your PDF files", "Click 'Browse Files' to pick individual PDFs, or 'Browse Folder' to select all PDFs inside a folder at once. The file list will preview your selection."),
                ("Enter the watermark text", "Type the text you want stamped on every page (e.g. CONFIDENTIAL, DRAFT, MSME). Leave it clear and short for best results."),
                ("Adjust font size", "Use the Font Size slider to make the watermark larger or smaller. Default is 120 — increase for bolder stamps."),
                ("Adjust rotation", "Use the Rotation slider to set the angle of the text. 45° is the standard diagonal. Set to 0° for horizontal."),
                ("Adjust opacity", "Use the Opacity slider to control how visible the watermark is. Lower values (e.g. 10–20%) are subtle; higher values are more prominent."),
                ("Choose a colour", "Select Gray, Black, Red, or Blue for the watermark text colour."),
                ("Click 'Apply Watermark'", "The tool processes all selected files. Progress is shown in the bar and log. Each file keeps its original name."),
                ("Find your files", "When done, the output folder opens automatically. Watermarked PDFs are saved to: Desktop → OUTPUT → PDF_Watermark → <timestamp folder>."),
            ],
            "tips": [
                "Short, uppercase text works best — long phrases may overflow the page.",
                "Opacity around 10–20% gives a professional subtle stamp; above 50% is very bold.",
                "Original files are never modified — watermarked copies are always saved to the OUTPUT folder.",
                "You can process an entire folder of PDFs at once using 'Browse Folder'.",
                "If a file fails (e.g. password-protected PDF), it is skipped and logged — other files still process normally.",
            ],
            "output": "Desktop\\OUTPUT\\PDF_Watermark\\YYYY-MM-DD_HH-MM-SS\\",
        },
    },
    {
        "title":       "Sticker Tool",
        "sample":      os.path.join(SAMPLES, "sample_sticker.xlsx"),
        "description": "Format Excel data into sticker sheets and generate a merged PDF using a Typst template.",
        "icon":        "🏷️",
        "accent":      C["orange"],
        "tag":         "PDF · Excel",
        "script":      os.path.join(SCRIPTS, "sticker_tool.py"),
        "docs": {
            "what": "Takes an Excel file, lets you pick which columns to use, then reformats the data into a sticker sheet layout (N stickers per sheet). It then generates a PDF for every row using a Typst template and merges all pages into a single ready-to-print PDF.",
            "when": "Use this when you have a list of records (names, barcodes, addresses, etc.) and need to print them as physical stickers or labels in a sheet format.",
            "steps": [
                ("Open the tool", "Click 'Launch →' on the Sticker Tool card from the Home screen."),
                ("Select your Excel file", "Click 'Browse' and pick the .xlsx file containing your sticker data. The tool will immediately read and display all available column names."),
                ("Select columns", "Tick the columns you want to include on the sticker (e.g. name, barcode, address). Untick any columns you don't need. Use 'Select All' or 'Clear All' to toggle quickly."),
                ("Set stickers per sheet", "Use the slider to choose how many stickers fit on one sheet. Default is 12. Adjust to match your physical sticker sheet layout."),
                ("Select a Typst template", "Click 'Browse' and pick a .typ template file. The template defines how each sticker looks. Placeholders like {{name}}, {{barcode}} in the template are filled from your Excel data."),
                ("Click 'Generate'", "The tool formats the Excel, generates one PDF per row using the template, then merges everything into a single stickers_merged.pdf. Progress and status show in the log."),
                ("Find your files", "When done, the output folder opens automatically with two files: sticker_formatted.xlsx (the reformatted data) and stickers_merged.pdf (ready to print)."),
            ],
            "tips": [
                "Column names in your Excel must match the placeholders in your Typst template exactly (case-sensitive).",
                "The stickers per sheet number should match your physical label sheet — common sizes are 12, 16, 20, or 24.",
                "Each run creates a new timestamped folder so previous outputs are never overwritten.",
                "If PDF generation fails but Excel succeeds, check that Typst is installed and your template has no syntax errors.",
                "You can re-use the formatted Excel (sticker_formatted.xlsx) directly if you want to run the PDF step again with a different template.",
            ],
            "output": "Desktop\\OUTPUT\\Sticker_Tool\\YYYY-MM-DD_HH-MM-SS\\",
        },
    },
    {
        "title":       "Excel ↔ JSON Converter",
        "sample":      None,
        "description": "Convert Excel files to structured JSON (clientInfo envelope) or JSON back to Excel / CSV.",
        "icon":        "🔄",
        "accent":      C["cyan"],
        "tag":         "Excel · JSON",
        "script":      os.path.join(SCRIPTS, "excel_json_converter.py"),
        "docs": {
            "what": "A two-way converter. Excel → JSON wraps your spreadsheet rows into a structured JSON file with a clientInfo envelope (status, total, clientInfo array). JSON → Excel / CSV flattens that JSON back into a spreadsheet, normalising nested fields automatically.",
            "when": "Use Excel → JSON when an API or system needs your data as a JSON file. Use JSON → Excel when you receive a JSON response and need to work with it in Excel or share it as a CSV.",
            "steps": [
                ("Select mode", "Choose 'Excel → JSON' or 'JSON → Excel / CSV' using the radio buttons at the top."),
                ("Select your file", "Click 'Browse…' and pick an Excel file (.xlsx/.xls) for Excel→JSON mode, or a .json file for JSON→Excel mode."),
                ("Set options (Excel → JSON)", "Optionally enter a sheet name. Leave blank to use the first sheet."),
                ("Set options (JSON → Excel)", "Tick the output formats you want — .xlsx, .csv, or both."),
                ("Click Convert", "The file is processed instantly. The log shows row count and output filenames."),
                ("Find your files", "The output folder opens automatically. Files are saved to: Desktop → OUTPUT → Excel_JSON_Converter → <timestamp>."),
            ],
            "tips": [
                "Excel → JSON: columns named 'status' and 'total' are promoted to top-level fields; all other columns become rows inside clientInfo.",
                "JSON → Excel: nested fields are flattened with underscore separators (e.g. address_city).",
                "Comma-formatted numbers in the debtRecordsAmount column are automatically cleaned to plain numbers.",
                "Each conversion creates a new timestamped folder so previous outputs are never overwritten.",
            ],
            "output": "Desktop\\OUTPUT\\Excel_JSON_Converter\\YYYY-MM-DD_HH-MM-SS\\",
        },
    },
    {
        "title":       "Excel Deduplicator",
        "sample":      None,
        "description": "Remove duplicate rows from an Excel file based on any column. Shows count of duplicates removed.",
        "icon":        "🧹",
        "accent":      C["green"],
        "tag":         "Excel",
        "script":      os.path.join(SCRIPTS, "excel_deduplicator.py"),
        "docs": {
            "what": "Reads an Excel file, removes duplicate rows based on a column you choose, and saves the cleaned file. You can pick whether to keep the first or last occurrence of each duplicate. The log shows exactly how many rows were removed.",
            "when": "Use this when you have an Excel sheet with repeated entries — for example customer records with the same customer_id appearing more than once — and you need a clean unique list.",
            "steps": [
                ("Open the tool", "Click 'Launch →' on the Excel Deduplicator card from the Home screen."),
                ("Select your Excel file", "Click 'Browse…' and pick the .xlsx or .xls file you want to clean. The tool will read and display all available column names as a hint."),
                ("Enter the column name", "Type the exact column header to deduplicate on (e.g. customer_id). If the file has a customer_id column, it is filled in automatically."),
                ("Choose which duplicate to keep", "Select 'First occurrence' to keep the earliest row, or 'Last occurrence' to keep the most recent one."),
                ("Click 'Remove Duplicates'", "The tool processes the file. The log shows rows loaded, duplicates removed, and unique rows kept."),
                ("Find your file", "When done, the output folder opens automatically. The cleaned file is saved as <original_name>_unique.xlsx."),
            ],
            "tips": [
                "Column names are case-sensitive — type them exactly as they appear in the header row.",
                "When the file is selected, the tool lists all detected column names as a hint below the entry box.",
                "Original files are never modified — the cleaned copy is always saved to a new timestamped output folder.",
                "Each run creates a new timestamped folder so previous outputs are never overwritten.",
            ],
            "output": "Desktop\\OUTPUT\\Excel_Deduplicator\\YYYY-MM-DD_HH-MM-SS\\",
        },
    },
    {
        "title":       "PDF Generation Pipeline",
        "sample":      None,
        "description": "Generate PDFs from Excel data using Typst templates. Supports multi-language, table rotation, merging, and S3 upload.",
        "icon":        "⚙️",
        "accent":      C["pink"],
        "tag":         "PDF · Typst · Excel",
        "script":      os.path.join(SCRIPTS, "pdf_generator", "ui.py"),
        "docs": {
            "what": "A full PDF generation pipeline. Reads rows from an Excel or CSV file, fills Typst (.typ) templates with per-row data, compiles each row into a PDF, and optionally merges all PDFs into batched output files. Supports multi-language templates (one .typ per language/state), table rotation (one PDF per applicant), password protection, and S3 upload.",
            "when": "Use this when you need to mass-generate personalised PDFs from a spreadsheet — for example notices, certificates, demand letters, or any document where each row produces its own PDF with the same template layout.",
            "steps": [
                ("Select your data file", "Click '…' next to 'Data file' and choose your .xlsx or .csv file. Each row becomes one PDF."),
                ("Select Notice Config (optional)", "If your templates use a JSON config (date formats, table definitions, decimal fields), browse and select it here. Leave blank for simple templates."),
                ("Set output folders", "The 'Output folder' is where individual PDFs are saved. 'Merge folder' is where batched merged PDFs go. Both default to folders inside the scripts directory."),
                ("Select template folder", "Click '…' next to 'Template folder' and choose the folder containing your .typ files and a template.json mapping file. The preview box will show all state/language → file mappings."),
                ("Configure template.json", 'Inside your template folder, create a template.json with a `template_dict` key: {"DEFAULT": "default.typ", "HINDI": "hindi.typ", ...}. The DEFAULT key is required.'),
                ("Set processing options", "Toggle 'Generate PDFs' and 'Merge PDFs' as needed. Adjust chunk size, batch size, max workers, and memory limit for your machine."),
                ("Enable S3 Upload (optional)", "Tick 'Enable S3 Upload', enter your S3 URI prefix, and ensure AWS credentials are in the .env file."),
                ("Run the pipeline", "Click '▶ Run Pipeline'. The log panel shows live progress. Use 'Save Config' to save your settings for next time."),
            ],
            "tips": [
                "template.json must be inside the selected template folder (or the scripts folder as fallback). It must have a `template_dict` object with at least a `DEFAULT` key.",
                "Column names in your Excel map directly to {{ColumnName}} placeholders in the .typ template.",
                "The pipeline resumes automatically if interrupted — it saves state after every 10 rows.",
                "Use 'Save Config' to export your current settings to a JSON file, then 'Load Config' on the next run.",
                "Output PDFs are saved in the Output folder. Merged batches go in the Merge folder. S3 uploads happen after merging.",
                "AWS credentials (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION, S3_BUCKET_NAME) should be in a .env file in the scripts folder.",
            ],
            "output": "Desktop\\OUTPUT\\  (individual PDFs)  |  MERGE_PDF\\  (batched merges)",
        },
    },
    {
        "title":       "S3 File Uploader",
        "sample":      None,
        "description": "Upload single or multiple files and folders to Amazon S3 with file type filtering.",
        "icon":        "☁️",
        "accent":      C["blue"],
        "tag":         "Cloud · S3",
        "script":      os.path.join(SCRIPTS, "s3_uploader.py"),
        "docs": {
            "what": "Uploads files to an Amazon S3 bucket in parallel. You can select individual files, multiple files, or entire folders (including subfolders). If your selection contains multiple file types, the tool lets you choose which types to upload.",
            "when": "Use this when you need to bulk-upload documents, PDFs, images, or any files to an S3 bucket without using the AWS console.",
            "steps": [
                ("Open the tool", "Click 'Launch →' on the S3 File Uploader card from the Home screen."),
                ("Add files or folders", "Click 'Add Files' to pick individual files, or 'Add Folders' to select a folder. You can click both buttons multiple times to keep adding more. Each item shows in the list with a remove (✕) button."),
                ("Filter by file type", "If your selection has multiple file types (e.g. .pdf and .xlsx), checkboxes appear for each type. Tick the ones you want to upload. If all files are the same type, this step is skipped automatically."),
                ("Enter the S3 upload path", "Type the folder path inside the bucket where files should go (e.g. uploads/documents/2024). Do not include the bucket name — that is loaded automatically."),
                ("Click 'Upload to S3'", "Files upload in parallel. The progress bar, stats (Uploaded / Failed / Skipped), and log update in real time."),
                ("Failed files", "If any files fail, they are automatically copied to Desktop → OUTPUT → S3_Upload → <timestamp> → failed\\ so you can retry them later."),
            ],
            "tips": [
                "Folders are scanned recursively — all files in subfolders are included automatically.",
                "Files are uploaded with the correct Content-Type (PDF, Excel, image, etc.) set automatically.",
                "Up to 8 files upload simultaneously for speed.",
                "The .env file must contain AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION, and S3_BUCKET_NAME.",
                "Original files are never moved or deleted — only copied to S3.",
            ],
            "output": "s3://<bucket>/<your-upload-path>/<filename>",
        },
    },
]
